// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AppendTransaction is the `appendTransaction` instruction.
type AppendTransaction struct {
	Bump         *uint8
	Instructions *TXInstruction
	Index        *uint64

	// [0] = [] smartWallet
	//
	// [1] = [WRITE] transaction
	//
	// [2] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewAppendTransactionInstructionBuilder creates a new `AppendTransaction` instruction builder.
func NewAppendTransactionInstructionBuilder() *AppendTransaction {
	nd := &AppendTransaction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *AppendTransaction) SetBump(bump uint8) *AppendTransaction {
	inst.Bump = &bump
	return inst
}

// SetInstructions sets the "instructions" parameter.
func (inst *AppendTransaction) SetInstructions(instructions TXInstruction) *AppendTransaction {
	inst.Instructions = &instructions
	return inst
}

// SetIndex sets the "index" parameter.
func (inst *AppendTransaction) SetIndex(index uint64) *AppendTransaction {
	inst.Index = &index
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *AppendTransaction) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *AppendTransaction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet).WRITE()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *AppendTransaction) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetTransactionAccount sets the "transaction" account.
func (inst *AppendTransaction) SetTransactionAccount(transaction ag_solanago.PublicKey) *AppendTransaction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(transaction).WRITE()
	return inst
}

// GetTransactionAccount gets the "transaction" account.
func (inst *AppendTransaction) GetTransactionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetOwnerAccount sets the "owner" account.
func (inst *AppendTransaction) SetOwnerAccount(owner ag_solanago.PublicKey) *AppendTransaction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *AppendTransaction) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

func (inst AppendTransaction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AppendTransaction,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AppendTransaction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AppendTransaction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.Instructions == nil {
			return errors.New("Instructions parameter is not set")
		}
		if inst.Index == nil {
			return errors.New("Index parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Transaction is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *AppendTransaction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AppendTransaction")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("        Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param("Instructions", *inst.Instructions))
						paramsBranch.Child(ag_format.Param("       Index", *inst.Index))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("transaction", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("      owner", inst.AccountMetaSlice[2]))
					})
				})
		})
}

func (obj AppendTransaction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Instructions` param:
	err = encoder.Encode(obj.Instructions)
	if err != nil {
		return err
	}
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AppendTransaction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Instructions`:
	err = decoder.Decode(&obj.Instructions)
	if err != nil {
		return err
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	return nil
}

// NewAppendTransactionInstruction declares a new AppendTransaction instruction with the provided parameters and accounts.
func NewAppendTransactionInstruction(
	// Parameters:
	bump uint8,
	instructions TXInstruction,
	index uint64,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	transaction ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *AppendTransaction {
	return NewAppendTransactionInstructionBuilder().
		SetBump(bump).
		SetInstructions(instructions).
		SetIndex(index).
		SetSmartWalletAccount(smartWallet).
		SetTransactionAccount(transaction).
		SetOwnerAccount(owner)
}

