// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "SmartWallet"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	Instruction_CreateSmartWallet = ag_binary.TypeID([8]byte{129, 39, 235, 18, 132, 68, 203, 19})

	Instruction_SetOwners = ag_binary.TypeID([8]byte{134, 145, 42, 122, 94, 64, 76, 218})

	Instruction_ChangeThreshold = ag_binary.TypeID([8]byte{146, 151, 213, 63, 121, 79, 9, 29})

	Instruction_CreateTransaction = ag_binary.TypeID([8]byte{227, 193, 53, 239, 55, 126, 112, 105})

	Instruction_AppendTransaction = ag_binary.TypeID([8]byte{47, 83, 162, 77, 7, 48, 55, 138})

	Instruction_CreateStake = ag_binary.TypeID([8]byte{201, 134, 55, 171, 2, 136, 228, 226})

	Instruction_RollupEntity = ag_binary.TypeID([8]byte{95, 120, 104, 158, 248, 66, 134, 145})

	Instruction_RegisterEntity = ag_binary.TypeID([8]byte{166, 52, 122, 244, 214, 116, 215, 255})

	Instruction_ClaimEntities = ag_binary.TypeID([8]byte{49, 64, 204, 122, 243, 46, 61, 49})

	Instruction_UpdateEntity = ag_binary.TypeID([8]byte{22, 25, 212, 236, 22, 130, 39, 73})

	Instruction_WithdrawEntity = ag_binary.TypeID([8]byte{117, 141, 134, 141, 159, 65, 75, 13})

	Instruction_CreateTransactionWithTimelock = ag_binary.TypeID([8]byte{93, 252, 41, 108, 86, 76, 89, 237})

	Instruction_Approve = ag_binary.TypeID([8]byte{69, 74, 217, 36, 115, 117, 97, 76})

	Instruction_Unapprove = ag_binary.TypeID([8]byte{5, 92, 229, 161, 250, 166, 122, 171})

	Instruction_ExecuteTransaction = ag_binary.TypeID([8]byte{231, 173, 49, 91, 235, 24, 68, 19})

	Instruction_ExecuteTransactionDerived = ag_binary.TypeID([8]byte{121, 1, 232, 181, 156, 185, 93, 88})

	Instruction_OwnerInvokeInstruction = ag_binary.TypeID([8]byte{204, 35, 69, 185, 159, 100, 140, 165})

	Instruction_CreateSubaccountInfo = ag_binary.TypeID([8]byte{196, 132, 49, 16, 91, 57, 67, 139})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_CreateSmartWallet:
		return "CreateSmartWallet"
	case Instruction_SetOwners:
		return "SetOwners"
	case Instruction_ChangeThreshold:
		return "ChangeThreshold"
	case Instruction_CreateTransaction:
		return "CreateTransaction"
	case Instruction_AppendTransaction:
		return "AppendTransaction"
	case Instruction_CreateStake:
		return "CreateStake"
	case Instruction_RollupEntity:
		return "RollupEntity"
	case Instruction_RegisterEntity:
		return "RegisterEntity"
	case Instruction_ClaimEntities:
		return "ClaimEntities"
	case Instruction_UpdateEntity:
		return "UpdateEntity"
	case Instruction_WithdrawEntity:
		return "WithdrawEntity"
	case Instruction_CreateTransactionWithTimelock:
		return "CreateTransactionWithTimelock"
	case Instruction_Approve:
		return "Approve"
	case Instruction_Unapprove:
		return "Unapprove"
	case Instruction_ExecuteTransaction:
		return "ExecuteTransaction"
	case Instruction_ExecuteTransactionDerived:
		return "ExecuteTransactionDerived"
	case Instruction_OwnerInvokeInstruction:
		return "OwnerInvokeInstruction"
	case Instruction_CreateSubaccountInfo:
		return "CreateSubaccountInfo"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			"create_smart_wallet", (*CreateSmartWallet)(nil),
		},
		{
			"set_owners", (*SetOwners)(nil),
		},
		{
			"change_threshold", (*ChangeThreshold)(nil),
		},
		{
			"create_transaction", (*CreateTransaction)(nil),
		},
		{
			"append_transaction", (*AppendTransaction)(nil),
		},
		{
			"create_stake", (*CreateStake)(nil),
		},
		{
			"rollup_entity", (*RollupEntity)(nil),
		},
		{
			"register_entity", (*RegisterEntity)(nil),
		},
		{
			"claim_entities", (*ClaimEntities)(nil),
		},
		{
			"update_entity", (*UpdateEntity)(nil),
		},
		{
			"withdraw_entity", (*WithdrawEntity)(nil),
		},
		{
			"create_transaction_with_timelock", (*CreateTransactionWithTimelock)(nil),
		},
		{
			"approve", (*Approve)(nil),
		},
		{
			"unapprove", (*Unapprove)(nil),
		},
		{
			"execute_transaction", (*ExecuteTransaction)(nil),
		},
		{
			"execute_transaction_derived", (*ExecuteTransactionDerived)(nil),
		},
		{
			"owner_invoke_instruction", (*OwnerInvokeInstruction)(nil),
		},
		{
			"create_subaccount_info", (*CreateSubaccountInfo)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
