// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RegisterEntity is the `registerEntity` instruction.
type RegisterEntity struct {
	Bump       *uint8
	TicketData *TicketData
	Mint       *ag_solanago.PublicKey

	// [0] = [WRITE] smartWallet
	//
	// [1] = [WRITE] ticket
	//
	// [2] = [WRITE, SIGNER] payer
	//
	// [3] = [SIGNER] owner
	//
	// [4] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewRegisterEntityInstructionBuilder creates a new `RegisterEntity` instruction builder.
func NewRegisterEntityInstructionBuilder() *RegisterEntity {
	nd := &RegisterEntity{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *RegisterEntity) SetBump(bump uint8) *RegisterEntity {
	inst.Bump = &bump
	return inst
}

// SetTicketData sets the "ticketData" parameter.
func (inst *RegisterEntity) SetTicketData(ticketData TicketData) *RegisterEntity {
	inst.TicketData = &ticketData
	return inst
}

// SetMint sets the "mint" parameter.
func (inst *RegisterEntity) SetMint(mint ag_solanago.PublicKey) *RegisterEntity {
	inst.Mint = &mint
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *RegisterEntity) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *RegisterEntity {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet).WRITE()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *RegisterEntity) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetTicketAccount sets the "ticket" account.
func (inst *RegisterEntity) SetTicketAccount(ticket ag_solanago.PublicKey) *RegisterEntity {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(ticket).WRITE()
	return inst
}

// GetTicketAccount gets the "ticket" account.
func (inst *RegisterEntity) GetTicketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetPayerAccount sets the "payer" account.
func (inst *RegisterEntity) SetPayerAccount(payer ag_solanago.PublicKey) *RegisterEntity {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *RegisterEntity) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetOwnerAccount sets the "owner" account.
func (inst *RegisterEntity) SetOwnerAccount(owner ag_solanago.PublicKey) *RegisterEntity {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *RegisterEntity) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RegisterEntity) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RegisterEntity {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RegisterEntity) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

func (inst RegisterEntity) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RegisterEntity,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RegisterEntity) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RegisterEntity) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.TicketData == nil {
			return errors.New("TicketData parameter is not set")
		}
		if inst.Mint == nil {
			return errors.New("Mint parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Ticket is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *RegisterEntity) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RegisterEntity")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("      Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param("TicketData", *inst.TicketData))
						paramsBranch.Child(ag_format.Param("      Mint", *inst.Mint))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("       ticket", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("        owner", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice[4]))
					})
				})
		})
}

func (obj RegisterEntity) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `TicketData` param:
	err = encoder.Encode(obj.TicketData)
	if err != nil {
		return err
	}
	// Serialize `Mint` param:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RegisterEntity) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `TicketData`:
	err = decoder.Decode(&obj.TicketData)
	if err != nil {
		return err
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return err
	}
	return nil
}

// NewRegisterEntityInstruction declares a new RegisterEntity instruction with the provided parameters and accounts.
func NewRegisterEntityInstruction(
	// Parameters:
	bump uint8,
	ticketData TicketData,
	mint ag_solanago.PublicKey,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	ticket ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *RegisterEntity {
	return NewRegisterEntityInstructionBuilder().
		SetBump(bump).
		SetTicketData(ticketData).
		SetMint(mint).
		SetSmartWalletAccount(smartWallet).
		SetTicketAccount(ticket).
		SetPayerAccount(payer).
		SetOwnerAccount(owner).
		SetSystemProgramAccount(systemProgram)
}
