// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RollupEntity is the `rollupEntity` instruction.
type RollupEntity struct {
	Bump *uint8
	Gid  *uint16

	// [0] = [WRITE] smartWallet
	//
	// [1] = [WRITE] rollup
	//
	// [2] = [WRITE, SIGNER] payer
	//
	// [3] = [SIGNER] owner
	//
	// [4] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewRollupEntityInstructionBuilder creates a new `RollupEntity` instruction builder.
func NewRollupEntityInstructionBuilder() *RollupEntity {
	nd := &RollupEntity{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *RollupEntity) SetBump(bump uint8) *RollupEntity {
	inst.Bump = &bump
	return inst
}

// SetGid sets the "gid" parameter.
func (inst *RollupEntity) SetGid(gid uint16) *RollupEntity {
	inst.Gid = &gid
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *RollupEntity) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *RollupEntity {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet).WRITE()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *RollupEntity) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetRollupAccount sets the "rollup" account.
func (inst *RollupEntity) SetRollupAccount(rollup ag_solanago.PublicKey) *RollupEntity {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(rollup).WRITE()
	return inst
}

// GetRollupAccount gets the "rollup" account.
func (inst *RollupEntity) GetRollupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetPayerAccount sets the "payer" account.
func (inst *RollupEntity) SetPayerAccount(payer ag_solanago.PublicKey) *RollupEntity {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *RollupEntity) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetOwnerAccount sets the "owner" account.
func (inst *RollupEntity) SetOwnerAccount(owner ag_solanago.PublicKey) *RollupEntity {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *RollupEntity) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RollupEntity) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RollupEntity {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RollupEntity) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

func (inst RollupEntity) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RollupEntity,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RollupEntity) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RollupEntity) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.Gid == nil {
			return errors.New("Gid parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Rollup is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *RollupEntity) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RollupEntity")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param(" Gid", *inst.Gid))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("       rollup", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("        owner", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice[4]))
					})
				})
		})
}

func (obj RollupEntity) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Gid` param:
	err = encoder.Encode(obj.Gid)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RollupEntity) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Gid`:
	err = decoder.Decode(&obj.Gid)
	if err != nil {
		return err
	}
	return nil
}

// NewRollupEntityInstruction declares a new RollupEntity instruction with the provided parameters and accounts.
func NewRollupEntityInstruction(
	// Parameters:
	bump uint8,
	gid uint16,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	rollup ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *RollupEntity {
	return NewRollupEntityInstructionBuilder().
		SetBump(bump).
		SetGid(gid).
		SetSmartWalletAccount(smartWallet).
		SetRollupAccount(rollup).
		SetPayerAccount(payer).
		SetOwnerAccount(owner).
		SetSystemProgramAccount(systemProgram)
}
