// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateEntityByOwner is the `updateEntityByOwner` instruction.
type UpdateEntityByOwner struct {
	Bump *uint8

	// [0] = [WRITE] smartWallet
	//
	// [1] = [WRITE] ticket
	//
	// [2] = [WRITE] rollup
	//
	// [3] = [WRITE, SIGNER] payer
	//
	// [4] = [WRITE, SIGNER] owner
	//
	// [5] = [WRITE] mint
	//
	// [6] = [] mintAta
	//
	// [7] = [] tokenProgram
	//
	// [8] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewUpdateEntityByOwnerInstructionBuilder creates a new `UpdateEntityByOwner` instruction builder.
func NewUpdateEntityByOwnerInstructionBuilder() *UpdateEntityByOwner {
	nd := &UpdateEntityByOwner{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 9),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *UpdateEntityByOwner) SetBump(bump uint8) *UpdateEntityByOwner {
	inst.Bump = &bump
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *UpdateEntityByOwner) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet).WRITE()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *UpdateEntityByOwner) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetTicketAccount sets the "ticket" account.
func (inst *UpdateEntityByOwner) SetTicketAccount(ticket ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(ticket).WRITE()
	return inst
}

// GetTicketAccount gets the "ticket" account.
func (inst *UpdateEntityByOwner) GetTicketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetRollupAccount sets the "rollup" account.
func (inst *UpdateEntityByOwner) SetRollupAccount(rollup ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(rollup).WRITE()
	return inst
}

// GetRollupAccount gets the "rollup" account.
func (inst *UpdateEntityByOwner) GetRollupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetPayerAccount sets the "payer" account.
func (inst *UpdateEntityByOwner) SetPayerAccount(payer ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *UpdateEntityByOwner) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetOwnerAccount sets the "owner" account.
func (inst *UpdateEntityByOwner) SetOwnerAccount(owner ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(owner).WRITE().SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *UpdateEntityByOwner) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

// SetMintAccount sets the "mint" account.
func (inst *UpdateEntityByOwner) SetMintAccount(mint ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mint).WRITE()
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *UpdateEntityByOwner) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[5]
}

// SetMintAtaAccount sets the "mintAta" account.
func (inst *UpdateEntityByOwner) SetMintAtaAccount(mintAta ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(mintAta)
	return inst
}

// GetMintAtaAccount gets the "mintAta" account.
func (inst *UpdateEntityByOwner) GetMintAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[6]
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *UpdateEntityByOwner) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *UpdateEntityByOwner) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[7]
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *UpdateEntityByOwner) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *UpdateEntityByOwner {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *UpdateEntityByOwner) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[8]
}

func (inst UpdateEntityByOwner) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateEntityByOwner,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateEntityByOwner) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateEntityByOwner) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Ticket is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Rollup is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.MintAta is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *UpdateEntityByOwner) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateEntityByOwner")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Bump", *inst.Bump))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=9]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("       ticket", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("       rollup", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("        owner", inst.AccountMetaSlice[4]))
						accountsBranch.Child(ag_format.Meta("         mint", inst.AccountMetaSlice[5]))
						accountsBranch.Child(ag_format.Meta("      mintAta", inst.AccountMetaSlice[6]))
						accountsBranch.Child(ag_format.Meta(" tokenProgram", inst.AccountMetaSlice[7]))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice[8]))
					})
				})
		})
}

func (obj UpdateEntityByOwner) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateEntityByOwner) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateEntityByOwnerInstruction declares a new UpdateEntityByOwner instruction with the provided parameters and accounts.
func NewUpdateEntityByOwnerInstruction(
	// Parameters:
	bump uint8,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	ticket ag_solanago.PublicKey,
	rollup ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	mintAta ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *UpdateEntityByOwner {
	return NewUpdateEntityByOwnerInstructionBuilder().
		SetBump(bump).
		SetSmartWalletAccount(smartWallet).
		SetTicketAccount(ticket).
		SetRollupAccount(rollup).
		SetPayerAccount(payer).
		SetOwnerAccount(owner).
		SetMintAccount(mint).
		SetMintAtaAccount(mintAta).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram)
}
