// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateEntity is the `updateEntity` instruction.
type UpdateEntity struct {
	Bump      *uint8
	Timestamp *[]byte

	// [0] = [WRITE] smartWallet
	//
	// [1] = [WRITE] ticket
	//
	// [2] = [WRITE] rollup
	//
	// [3] = [WRITE, SIGNER] payer
	//
	// [4] = [SIGNER] smartWalletOwner
	//
	// [5] = [] mint
	//
	// [6] = [] tokenProgram
	//
	// [7] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewUpdateEntityInstructionBuilder creates a new `UpdateEntity` instruction builder.
func NewUpdateEntityInstructionBuilder() *UpdateEntity {
	nd := &UpdateEntity{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *UpdateEntity) SetBump(bump uint8) *UpdateEntity {
	inst.Bump = &bump
	return inst
}

// SetTimestamp sets the "timestamp" parameter.
func (inst *UpdateEntity) SetTimestamp(timestamp []byte) *UpdateEntity {
	inst.Timestamp = &timestamp
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *UpdateEntity) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet).WRITE()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *UpdateEntity) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetTicketAccount sets the "ticket" account.
func (inst *UpdateEntity) SetTicketAccount(ticket ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(ticket).WRITE()
	return inst
}

// GetTicketAccount gets the "ticket" account.
func (inst *UpdateEntity) GetTicketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetRollupAccount sets the "rollup" account.
func (inst *UpdateEntity) SetRollupAccount(rollup ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(rollup).WRITE()
	return inst
}

// GetRollupAccount gets the "rollup" account.
func (inst *UpdateEntity) GetRollupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetPayerAccount sets the "payer" account.
func (inst *UpdateEntity) SetPayerAccount(payer ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *UpdateEntity) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetSmartWalletOwnerAccount sets the "smartWalletOwner" account.
func (inst *UpdateEntity) SetSmartWalletOwnerAccount(smartWalletOwner ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(smartWalletOwner).SIGNER()
	return inst
}

// GetSmartWalletOwnerAccount gets the "smartWalletOwner" account.
func (inst *UpdateEntity) GetSmartWalletOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

// SetMintAccount sets the "mint" account.
func (inst *UpdateEntity) SetMintAccount(mint ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *UpdateEntity) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[5]
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *UpdateEntity) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *UpdateEntity) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[6]
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *UpdateEntity) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *UpdateEntity {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *UpdateEntity) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[7]
}

func (inst UpdateEntity) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateEntity,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateEntity) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateEntity) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.Timestamp == nil {
			return errors.New("Timestamp parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Ticket is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Rollup is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SmartWalletOwner is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *UpdateEntity) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateEntity")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("     Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param("Timestamp", *inst.Timestamp))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("          ticket", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("          rollup", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("           payer", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("smartWalletOwner", inst.AccountMetaSlice[4]))
						accountsBranch.Child(ag_format.Meta("            mint", inst.AccountMetaSlice[5]))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice[6]))
						accountsBranch.Child(ag_format.Meta("   systemProgram", inst.AccountMetaSlice[7]))
					})
				})
		})
}

func (obj UpdateEntity) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Timestamp` param:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateEntity) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateEntityInstruction declares a new UpdateEntity instruction with the provided parameters and accounts.
func NewUpdateEntityInstruction(
	// Parameters:
	bump uint8,
	timestamp []byte,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	ticket ag_solanago.PublicKey,
	rollup ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	smartWalletOwner ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *UpdateEntity {
	return NewUpdateEntityInstructionBuilder().
		SetBump(bump).
		SetTimestamp(timestamp).
		SetSmartWalletAccount(smartWallet).
		SetTicketAccount(ticket).
		SetRollupAccount(rollup).
		SetPayerAccount(payer).
		SetSmartWalletOwnerAccount(smartWalletOwner).
		SetMintAccount(mint).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram)
}
