// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// WithdrawEntity is the `withdrawEntity` instruction.
type WithdrawEntity struct {
	Bump *uint8
	Mint *ag_solanago.PublicKey

	// [0] = [WRITE] smartWallet
	//
	// [1] = [WRITE] stake
	//
	// [2] = [WRITE] ticket
	//
	// [3] = [WRITE, SIGNER] payer
	//
	// [4] = [SIGNER] owner
	//
	// [5] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewWithdrawEntityInstructionBuilder creates a new `WithdrawEntity` instruction builder.
func NewWithdrawEntityInstructionBuilder() *WithdrawEntity {
	nd := &WithdrawEntity{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *WithdrawEntity) SetBump(bump uint8) *WithdrawEntity {
	inst.Bump = &bump
	return inst
}

// SetMint sets the "mint" parameter.
func (inst *WithdrawEntity) SetMint(mint ag_solanago.PublicKey) *WithdrawEntity {
	inst.Mint = &mint
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *WithdrawEntity) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *WithdrawEntity {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet).WRITE()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *WithdrawEntity) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetStakeAccount sets the "stake" account.
func (inst *WithdrawEntity) SetStakeAccount(stake ag_solanago.PublicKey) *WithdrawEntity {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stake).WRITE()
	return inst
}

// GetStakeAccount gets the "stake" account.
func (inst *WithdrawEntity) GetStakeAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetTicketAccount sets the "ticket" account.
func (inst *WithdrawEntity) SetTicketAccount(ticket ag_solanago.PublicKey) *WithdrawEntity {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(ticket).WRITE()
	return inst
}

// GetTicketAccount gets the "ticket" account.
func (inst *WithdrawEntity) GetTicketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetPayerAccount sets the "payer" account.
func (inst *WithdrawEntity) SetPayerAccount(payer ag_solanago.PublicKey) *WithdrawEntity {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *WithdrawEntity) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetOwnerAccount sets the "owner" account.
func (inst *WithdrawEntity) SetOwnerAccount(owner ag_solanago.PublicKey) *WithdrawEntity {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *WithdrawEntity) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *WithdrawEntity) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *WithdrawEntity {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *WithdrawEntity) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[5]
}

func (inst WithdrawEntity) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_WithdrawEntity,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst WithdrawEntity) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *WithdrawEntity) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.Mint == nil {
			return errors.New("Mint parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Stake is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Ticket is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *WithdrawEntity) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("WithdrawEntity")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param("Mint", *inst.Mint))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("        stake", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("       ticket", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("        owner", inst.AccountMetaSlice[4]))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice[5]))
					})
				})
		})
}

func (obj WithdrawEntity) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Mint` param:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return err
	}
	return nil
}
func (obj *WithdrawEntity) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return err
	}
	return nil
}

// NewWithdrawEntityInstruction declares a new WithdrawEntity instruction with the provided parameters and accounts.
func NewWithdrawEntityInstruction(
	// Parameters:
	bump uint8,
	mint ag_solanago.PublicKey,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	stake ag_solanago.PublicKey,
	ticket ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	owner ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *WithdrawEntity {
	return NewWithdrawEntityInstructionBuilder().
		SetBump(bump).
		SetMint(mint).
		SetSmartWalletAccount(smartWallet).
		SetStakeAccount(stake).
		SetTicketAccount(ticket).
		SetPayerAccount(payer).
		SetOwnerAccount(owner).
		SetSystemProgramAccount(systemProgram)
}
