// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ExecuteTransaction is the `executeTransaction` instruction.
type ExecuteTransaction struct {

	// [0] = [] smartWallet
	//
	// [1] = [WRITE] transaction
	//
	// [2] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewExecuteTransactionInstructionBuilder creates a new `ExecuteTransaction` instruction builder.
func NewExecuteTransactionInstructionBuilder() *ExecuteTransaction {
	nd := &ExecuteTransaction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *ExecuteTransaction) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *ExecuteTransaction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet)
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *ExecuteTransaction) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetTransactionAccount sets the "transaction" account.
func (inst *ExecuteTransaction) SetTransactionAccount(transaction ag_solanago.PublicKey) *ExecuteTransaction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(transaction).WRITE()
	return inst
}

// GetTransactionAccount gets the "transaction" account.
func (inst *ExecuteTransaction) GetTransactionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetOwnerAccount sets the "owner" account.
func (inst *ExecuteTransaction) SetOwnerAccount(owner ag_solanago.PublicKey) *ExecuteTransaction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *ExecuteTransaction) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

func (inst ExecuteTransaction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ExecuteTransaction,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ExecuteTransaction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ExecuteTransaction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Transaction is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *ExecuteTransaction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ExecuteTransaction")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("transaction", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("      owner", inst.AccountMetaSlice[2]))
					})
				})
		})
}

func (obj ExecuteTransaction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *ExecuteTransaction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewExecuteTransactionInstruction declares a new ExecuteTransaction instruction with the provided parameters and accounts.
func NewExecuteTransactionInstruction(
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	transaction ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *ExecuteTransaction {
	return NewExecuteTransactionInstructionBuilder().
		SetSmartWalletAccount(smartWallet).
		SetTransactionAccount(transaction).
		SetOwnerAccount(owner)
}
