// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package smart_wallet

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// OwnerInvokeInstruction is the `ownerInvokeInstruction` instruction.
type OwnerInvokeInstruction struct {
	Index *uint64
	Bump  *uint8
	Ix    *TXInstruction

	// [0] = [] smartWallet
	//
	// [1] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewOwnerInvokeInstructionInstructionBuilder creates a new `OwnerInvokeInstruction` instruction builder.
func NewOwnerInvokeInstructionInstructionBuilder() *OwnerInvokeInstruction {
	nd := &OwnerInvokeInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetIndex sets the "index" parameter.
func (inst *OwnerInvokeInstruction) SetIndex(index uint64) *OwnerInvokeInstruction {
	inst.Index = &index
	return inst
}

// SetBump sets the "bump" parameter.
func (inst *OwnerInvokeInstruction) SetBump(bump uint8) *OwnerInvokeInstruction {
	inst.Bump = &bump
	return inst
}

// SetIx sets the "ix" parameter.
func (inst *OwnerInvokeInstruction) SetIx(ix TXInstruction) *OwnerInvokeInstruction {
	inst.Ix = &ix
	return inst
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *OwnerInvokeInstruction) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *OwnerInvokeInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(smartWallet)
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *OwnerInvokeInstruction) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetOwnerAccount sets the "owner" account.
func (inst *OwnerInvokeInstruction) SetOwnerAccount(owner ag_solanago.PublicKey) *OwnerInvokeInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *OwnerInvokeInstruction) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

func (inst OwnerInvokeInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_OwnerInvokeInstruction,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst OwnerInvokeInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *OwnerInvokeInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Index == nil {
			return errors.New("Index parameter is not set")
		}
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
		if inst.Ix == nil {
			return errors.New("Ix parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *OwnerInvokeInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("OwnerInvokeInstruction")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Index", *inst.Index))
						paramsBranch.Child(ag_format.Param(" Bump", *inst.Bump))
						paramsBranch.Child(ag_format.Param("   Ix", *inst.Ix))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("smartWallet", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("      owner", inst.AccountMetaSlice[1]))
					})
				})
		})
}

func (obj OwnerInvokeInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Ix` param:
	err = encoder.Encode(obj.Ix)
	if err != nil {
		return err
	}
	return nil
}
func (obj *OwnerInvokeInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Ix`:
	err = decoder.Decode(&obj.Ix)
	if err != nil {
		return err
	}
	return nil
}

// NewOwnerInvokeInstructionInstruction declares a new OwnerInvokeInstruction instruction with the provided parameters and accounts.
func NewOwnerInvokeInstructionInstruction(
	// Parameters:
	index uint64,
	bump uint8,
	ix TXInstruction,
	// Accounts:
	smartWallet ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *OwnerInvokeInstruction {
	return NewOwnerInvokeInstructionInstructionBuilder().
		SetIndex(index).
		SetBump(bump).
		SetIx(ix).
		SetSmartWalletAccount(smartWallet).
		SetOwnerAccount(owner)
}
